#! /bin/bash
cd ~/cpp_code_review

echo "----------------------- 本地库状态 -----------------------"
git status

echo ""

echo -n "正在提交备注...，请填写备注（可空）"
read remarks

if [ ! -n "$remarks" ];then
	remarks="$(date +%m-%d\ %H:%M)"
fi

git add .

git commit -m "$remarks"

echo ""
echo "----------------------- 提交结果 -----------------------"
git push

echo ""

